### ISSUE TITLE
Getting this when trying to run todo.go

### ISSUE THREAD

**Issue by dky** [skadimoolam/go-vue-todos#3]
todo.go:5:2: cannot find package "go-echo-vue/handlers" in any of:
    /usr/local/Cellar/go/1.7.1/libexec/src/go-echo-vue/handlers (from $GOROOT)
    /Users/dky/go/src/go-echo-vue/handlers (from $GOPATH)

**Comment by jose-neta** [comment]
@dky https://github.com/skadimoolam/go-vue-todos/pull/4 fixes it

**Comment by skadimoolam** [comment]
This has been fixed now, please try it again.

**Comment by dky** [comment]
Thx, resolved.
