### ISSUE TITLE
when run todo.go,get error msgs like below:

### ISSUE THREAD

**Issue by wuchangfeng** [skadimoolam/go-vue-todos#9]
thx for your porject, but when i clone your project and follow the installions,at the last  got this error msg:

➜  go-vue-todos git:(master) go run todo.go
todo.go:8:2: cannot find package "github.com/labstack/echo/engine/standard" in any of:
	/usr/local/go/src/github.com/labstack/echo/engine/standard (from $GOROOT)
	/Users/allenwu/GoProjects/src/github.com/labstack/echo/engine/standard (from $GOPATH)

I had checked issues and pr,but nothing about the error.

**Comment by nowilike** [comment]
It seems that echo has changed something.
I commented this:
	//"github.com/labstack/echo/engine/standard"
and changed 
        e.Run(standard.New(":8080"))
to
        e.Start(":8080")

**Comment by Trashed** [comment]
I left a pull request and I made changes @nowilike mentioned.

**Comment by skadimoolam** [comment]
This has since been updated.
